baseURL = "https://jtiai.github.io/"
languageCode = "en-us"
title = "Janze Magik"
theme = "hugo-theme-relearn"

[outputs]
home = ["HTML", "RSS", "SEARCH"]

[params]
    disableInlineCopyToClipBoard = true
